/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/Components/HelloWorld.vue')['default']
    HomeSearchBar: typeof import('./src/Components/HomeSearchBar.vue')['default']
    IconCommunity: typeof import('./src/Components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/Components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/Components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/Components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/Components/icons/IconTooling.vue')['default']
    JobCard: typeof import('./src/Components/JobCard.vue')['default']
    JobDetail: typeof import('./src/Components/JobDetail.vue')['default']
    JobListing: typeof import('./src/Components/JobListing.vue')['default']
    JobSearchItem: typeof import('./src/Components/JobSearchItem.vue')['default']
    Pagination: typeof import('./src/Components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/Components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/Components/WelcomeItem.vue')['default']
  }
}
