/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressInfo: typeof import('./src/Components/ProfileFormSteps/AddressInfo.vue')['default']
    BasicInfo: typeof import('./src/Components/ProfileFormSteps/BasicInfo.vue')['default']
    ContactInfo: typeof import('./src/Components/ProfileFormSteps/ContactInfo.vue')['default']
    HelloWorld: typeof import('./src/Components/HelloWorld.vue')['default']
    HomeSearchBar: typeof import('./src/Components/HomeSearchBar.vue')['default']
    IconCommunity: typeof import('./src/Components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/Components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/Components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/Components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/Components/icons/IconTooling.vue')['default']
    Index: typeof import('./src/Components/ProfileFormSteps/Index.vue')['default']
    JobCard: typeof import('./src/Components/JobCard.vue')['default']
    JobDetail: typeof import('./src/Components/JobDetail.vue')['default']
    JobSearchItem: typeof import('./src/Components/JobSearchItem.vue')['default']
    Pagination: typeof import('./src/Components/Pagination.vue')['default']
    PhoneInput: typeof import('./src/Components/PhoneInput.vue')['default']
    ProfileCard: typeof import('./src/Components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/Components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/Components/WelcomeItem.vue')['default']
  }
}
