[build]
  publish = "dist"
  command = "yarn build"

# API proxy - MUST come before the SPA fallback
[[redirects]]
  from = "/api/*"
  to = "https://job-portal-backend-a3ux.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


