[build]
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "https://job-portal-backend-a3ux.onrender.com/:splat"  # Remove `/api` prefix here
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*",
    X-Forwarded-Host = "careerhubpk.netlify.app" 
  }

  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


