/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressInfo: typeof import('./../components/ProfileFormSteps/AddressInfo.vue')['default']
    BasicInfo: typeof import('./../components/ProfileFormSteps/BasicInfo.vue')['default']
    ContactInfo: typeof import('./../components/ProfileFormSteps/ContactInfo.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomeSearchBar: typeof import('./../components/HomeSearchBar.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Index: typeof import('./../components/ProfileFormSteps/Index.vue')['default']
    JobCard: typeof import('./../components/JobCard.vue')['default']
    JobDetail: typeof import('./../components/JobDetail.vue')['default']
    JobSearchItem: typeof import('./../components/JobSearchItem.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    PhoneInput: typeof import('./../components/PhoneInput.vue')['default']
    ProfileCard: typeof import('./../components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
