/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../Components/HelloWorld.vue')['default']
    HomeSearchBar: typeof import('./../Components/HomeSearchBar.vue')['default']
    IconsIconCommunity: typeof import('./../Components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../Components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../Components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../Components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../Components/icons/IconTooling.vue')['default']
    JobCard: typeof import('./../Components/JobCard.vue')['default']
    JobDetail: typeof import('./../Components/JobDetail.vue')['default']
    JobSearchItem: typeof import('./../Components/JobSearchItem.vue')['default']
    Pagination: typeof import('./../Components/Pagination.vue')['default']
    PhoneInput: typeof import('./../Components/PhoneInput.vue')['default']
    ProfileCard: typeof import('./../Components/ProfileCard.vue')['default']
    ProfileFormSteps: typeof import('./../Components/ProfileFormSteps/Index.vue')['default']
    ProfileFormStepsAddressInfo: typeof import('./../Components/ProfileFormSteps/AddressInfo.vue')['default']
    ProfileFormStepsBasicInfo: typeof import('./../Components/ProfileFormSteps/BasicInfo.vue')['default']
    ProfileFormStepsContactInfo: typeof import('./../Components/ProfileFormSteps/ContactInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../Components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../Components/WelcomeItem.vue')['default']
  }
}
